/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomeAcceptModal: typeof import('./src/components/home/homeAcceptModal.vue')['default']
    HomeSwiper: typeof import('./src/components/home/homeSwiper.vue')['default']
    HomeTransferModal: typeof import('./src/components/home/homeTransferModal.vue')['default']
    InputNumber: typeof import('./src/components/inputNumber.vue')['default']
    InputString: typeof import('./src/components/inputString.vue')['default']
    NavBar: typeof import('./src/components/navBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanQRCode: typeof import('./src/components/scanQRCode.vue')['default']
    ValidatePassword: typeof import('./src/components/validatePassword.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCol: typeof import('vant/es')['Col']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRow: typeof import('vant/es')['Row']
    VanSlider: typeof import('vant/es')['Slider']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
    WalletList: typeof import('./src/components/home/walletList.vue')['default']
  }
}
